# render.yaml

databases:
  - name: garden_db
    databaseName: garden_production
    user: garden_user
    plan: free

services:
  - type: web
    name: garden-api
    runtime: ruby
    buildCommand: |
      gem update --system -N --force --silent
      gem install bundler -v 2.6.6
      bundle config set force_ruby_platform true
      bundle lock --add-platform x86_64-linux
      bundle _2.6.6_ install
      # Uncomment the line below only if your app requires asset precompilation.
      # bundle exec rake assets:precompile
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production
    plan: free
