default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: williamlin  # ← Replace with your macOS username
  password:             # Leave blank if no password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: garden_api_development

test:
  <<: *default
  database: garden_api_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000